---
title: "Data Visualization I"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

## Upload the Data

```{r}

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```
## Make Our First Plot :)

```{r}

ggp_weather_scatterplot = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggp_weather_scatterplot

```

## Fancier Scatterplots!

```{r}

ggp_weather_scatterplot_2 = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5, size = 0.8) + 
  geom_smooth(se = FALSE)

ggp_weather_scatterplot_2

```
Where you define the aesthetics can matter:

```{r}

ggp_weather_scatterplot_2.1 = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5, size = 0.8) + 
  geom_smooth(se = FALSE)

ggp_weather_scatterplot_2.1

```

Let's use faceting real quick:

```{r}

ggp_weather_scatterplot_2.2 = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5, size = 0.8) + 
  geom_smooth(se = FALSE) + 
  facet_grid (. ~ name)

ggp_weather_scatterplot_2.2

```

## A More Interesting Scatterplot

```{r}

ggp_weather_scatterplot_3 = 
  weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name, size = prcp)) + 
  geom_point(alpha = 0.5) + 
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)

ggp_weather_scatterplot_3


```

## Learning Assessment

```{r}

ggp_weather_LA_plot = 
  weather_df %>%
  filter(name == "CentralPark_NY") %>%
  mutate(tmax_F = tmax * (9/5) + 32,
         tmin_F = tmin * (9/5) + 32) %>%
  ggplot(aes(x = tmin_F, y = tmax_F)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

ggp_weather_LA_plot

```

